export const LANGUAGES = [
  { code: "en", country: "US", name: "English", native: "English" },
  { code: "es", country: "AR", name: "Español", native: "Español" },
  { code: "pt", country: "BR", name: "Português", native: "Português" },
  { code: "en", country: "CA", name: "English", native: "English" },
  { code: "fr", country: "CA", name: "Français", native: "Français" },
  { code: "es", country: "CO", name: "Español", native: "Español" },
  { code: "cs", country: "CZ", name: "Čeština", native: "Čeština" },
  { code: "da", country: "DK", name: "Dansk", native: "Dansk" },
  { code: "de", country: "DE", name: "Deutsch", native: "Deutsch" },
  { code: "et", country: "EE", name: "Eesti", native: "Eesti" },
  { code: "el", country: "GR", name: "Ελληνικά", native: "Ελληνικά" },
  { code: "es", country: "ES", name: "Español", native: "Español" },
  { code: "fr", country: "FR", name: "Français", native: "Français" },
  { code: "hr", country: "HR", name: "Hrvatski", native: "Hrvatski" },
  { code: "hi", country: "IN", name: "हिंदी", native: "हिंदी" },
  { code: "en", country: "IN", name: "English", native: "English" },
  { code: "id", country: "ID", name: "Bahasa Indonesia", native: "Bahasa Indonesia" },
  { code: "it", country: "IT", name: "Italiano", native: "Italiano" },
  { code: "ja", country: "JP", name: "日本語", native: "日本語" },
  { code: "lv", country: "LV", name: "Latviešu", native: "Latviešu" },
  { code: "lt", country: "LT", name: "Lietuvių", native: "Lietuvių" },
  { code: "hu", country: "HU", name: "Magyar", native: "Magyar" },
  { code: "en", country: "MY", name: "English", native: "English" },
  { code: "es", country: "MX", name: "Español", native: "Español" },
  { code: "en", country: "NG", name: "English", native: "English" },
  { code: "nl", country: "NL", name: "Nederlands", native: "Nederlands" },
  { code: "no", country: "NO", name: "Norsk", native: "Norsk" },
  { code: "en", country: "PK", name: "English", native: "English" },
  { code: "en", country: "PH", name: "English", native: "English" },
  { code: "pl", country: "PL", name: "Polski", native: "Polski" },
  { code: "pt", country: "PT", name: "Português", native: "Português" },
  { code: "ro", country: "RO", name: "Română", native: "Română" },
  { code: "sk", country: "SK", name: "Slovenčina", native: "Slovenčina" },
  { code: "fi", country: "FI", name: "Suomi", native: "Suomi" },
  { code: "sv", country: "SE", name: "Svenska", native: "Svenska" },
  { code: "tr", country: "TR", name: "Türkçe", native: "Türkçe" },
  { code: "uk", country: "UA", name: "Українська", native: "Українська" },
  { code: "en", country: "GB", name: "English", native: "English" },
  { code: "vi", country: "VN", name: "Tiếng Việt", native: "Tiếng Việt" },
  { code: "ar", country: "AE", name: "العربية", native: "العربية" },
  { code: "he", country: "IL", name: "עברית", native: "עברית" },
  { code: "th", country: "TH", name: "ไทย", native: "ไทย" },
  { code: "ko", country: "KR", name: "한국어", native: "한국어" },
  { code: "zh", country: "CN", name: "中文", native: "中文" },
];

export const getCountryName = (code: string) => {
  const countryNames: Record<string, string> = {
    US: "United States",
    AR: "Argentina",
    BR: "Brasil",
    CA: "Canada",
    CO: "Colombia",
    CZ: "Česko",
    DK: "Danmark",
    DE: "Deutschland",
    EE: "Eesti",
    GR: "Ελλάδα",
    ES: "España",
    FR: "France",
    HR: "Hrvatska",
    IN: "India",
    ID: "Indonesia",
    IT: "Italia",
    JP: "Japan",
    LV: "Latvija",
    LT: "Lietuva",
    HU: "Magyarország",
    MY: "Malaysia",
    MX: "México",
    NG: "Nigeria",
    NL: "Nederland",
    NO: "Norge",
    PK: "Pakistan",
    PH: "Philippines",
    PL: "Polska",
    PT: "Portugal",
    RO: "Română",
    SK: "Slovensko",
    FI: "Suomi",
    SE: "Sverige",
    TR: "Türkiye",
    UA: "Україна",
    GB: "United Kingdom",
    VN: "Việt Nam",
    AE: "الدول العربية",
    IL: "יִשְׂרָאֵל",
    TH: "ประเทศไทย",
    KR: "대한민국",
    CN: "中国",
  };
  return countryNames[code] || code;
};

export const detectBrowserLanguage = (): string => {
  const browserLang = navigator.language?.split("-")[0] || "en";
  const supported = LANGUAGES.map((l) => l.code);
  return supported.includes(browserLang) ? browserLang : "en";
};
