export interface PricingPlan {
  name: string;
  price: number;
  originalPrice: number;
  discount: string;
  billing: string;
  description: string;
  popular?: boolean;
  features: string[];
  cta: string;
}

export interface HostingType {
  label: string;
  plans: PricingPlan[];
}

export const hostingTypes: { [key: string]: HostingType } = {
  "direct-admin-hosting": {
    label: "Direct Admin Hosting",
    plans: [
      {
        name: "Starter",
        price: 500,
        originalPrice: 500,
        discount: "",
        billing: "/month (₦)",
        description: "Perfect for small websites",
        features: [
          "1 GB SSD storage",
          "Unlimited bandwidth",
          "Support for 2 domains",
          "12 email accounts",
          "12 MySQL databases",
          "Free SSL certificate",
          "DirectAdmin control panel",
          "24/7 Nigerian support",
          "Free website migration",
          "99.9% uptime guarantee",
          "Daily automatic backups",
          "Password protected directories",
        ],
        cta: "Get started",
      },
      {
        name: "Premium",
        price: 1500,
        originalPrice: 1500,
        discount: "",
        billing: "/month (₦)",
        description: "Best for growing businesses",
        popular: true,
        features: [
          "5 GB SSD storage",
          "Unlimited bandwidth",
          "Support for 5 domains",
          "100 email accounts",
          "Unlimited MySQL databases",
          "Free SSL certificate",
          "DirectAdmin control panel",
          "24/7 priority support",
          "Free unlimited migrations",
          "99.9% uptime guarantee",
          "Daily automatic backups",
          "Advanced FTP access",
          "Git version control",
        ],
        cta: "Get started",
      },
      {
        name: "Enterprise",
        price: 4500,
        originalPrice: 4500,
        discount: "",
        billing: "/month (₦)",
        description: "For high-traffic websites",
        features: [
          "Unlimited SSD storage",
          "Unlimited bandwidth",
          "Unlimited domains",
          "Unlimited email accounts",
          "Unlimited MySQL databases",
          "Free SSL certificate",
          "DirectAdmin control panel",
          "24/7 dedicated support",
          "Free unlimited migrations",
          "99.99% uptime SLA",
          "Hourly automatic backups",
          "Advanced FTP & SSH access",
          "API access",
        ],
        cta: "Get started",
      },
    ],
  },
  "cpanel-hosting": {
    label: "cPanel Hosting",
    plans: [
      {
        name: "NH cPanel Lite",
        price: 1500,
        originalPrice: 1500,
        discount: "",
        billing: "/month (₦)",
        description: "Perfect for small websites and blogs",
        features: [
          "5 GB NVMe SSD storage",
          "Unlimited bandwidth",
          "1 primary domain",
          "15 sub-domains",
          "12 email accounts",
          "12 MySQL databases",
          "10,000 inodes",
          "Free SSL certificate",
          "cPanel control panel",
          "Softaculous (400+ apps)",
          "24/7 Nigerian support",
          "Daily automatic backups",
          "99.9% uptime guarantee",
        ],
        cta: "Get started",
      },
      {
        name: "NH cPanel Plus",
        price: 2500,
        originalPrice: 2500,
        discount: "",
        billing: "/month (₦)",
        description: "Best for growing businesses",
        popular: true,
        features: [
          "15 GB SSD storage",
          "Unlimited bandwidth",
          "3 primary domains",
          "12 sub-domains",
          "20 email accounts",
          "100 MySQL databases",
          "Unlimited inodes",
          "Free SSL certificate",
          "cPanel control panel",
          "Softaculous (400+ apps)",
          "24/7 priority support",
          "Daily automatic backups",
          "Free website migration",
          "99.9% uptime guarantee",
        ],
        cta: "Get started",
      },
      {
        name: "NH cPanel Turbo",
        price: 5500,
        originalPrice: 5500,
        discount: "",
        billing: "/month (₦)",
        description: "For high-performance websites",
        features: [
          "Unlimited NVMe SSD storage",
          "Unlimited bandwidth",
          "10 primary domains",
          "30 sub-domains",
          "Unlimited email accounts",
          "Unlimited MySQL databases",
          "Unlimited inodes",
          "Free SSL certificates",
          "cPanel control panel",
          "Softaculous (400+ apps)",
          "24/7 dedicated support",
          "Hourly automatic backups",
          "Free unlimited migrations",
          "99.99% uptime SLA",
        ],
        cta: "Get started",
      },
    ],
  },
  "reseller-hosting": {
    label: "Reseller Hosting",
    plans: [
      {
        name: "Starter Reseller",
        price: 7000,
        originalPrice: 7000,
        discount: "",
        billing: "/month (₦)",
        description: "Perfect for freelancers",
        features: [
          "70 GB SSD storage",
          "Host up to 30 client accounts",
          "100,000 monthly bandwidth",
          "Unlimited email accounts",
          "Free domain",
          "Free SSL certificates",
          "DirectAdmin & cPanel variants",
          "WHMCS billing included",
          "Private nameservers",
          "100% white-label",
          "Overselling enabled",
          "24/7 Nigerian support",
          "99.9% uptime guarantee",
          "DDoS Protection",
        ],
        cta: "Get started",
      },
      {
        name: "Pro Reseller",
        price: 12500,
        originalPrice: 12500,
        discount: "",
        billing: "/month (₦)",
        description: "Best for agencies",
        popular: true,
        features: [
          "200 GB SSD storage",
          "Host up to 100 client accounts",
          "Unlimited monthly bandwidth",
          "Unlimited email accounts",
          "Free domain",
          "Unlimited SSL certificates",
          "DirectAdmin & cPanel variants",
          "WHMCS billing included",
          "Private nameservers",
          "100% white-label solution",
          "Overselling enabled",
          "24/7 priority support",
          "99.9% uptime guarantee",
          "DDoS Protection",
        ],
        cta: "Get started",
      },
      {
        name: "Enterprise Reseller",
        price: 20000,
        originalPrice: 20000,
        discount: "",
        billing: "/month (₦)",
        description: "For large-scale operations",
        features: [
          "300 GB SSD storage",
          "Host up to 200 client accounts",
          "Unlimited monthly bandwidth",
          "Unlimited email accounts",
          "Free domain",
          "Unlimited SSL certificates",
          "DirectAdmin & cPanel variants",
          "WHMCS billing included",
          "Private nameservers",
          "100% white-label solution",
          "Overselling enabled",
          "24/7 dedicated support",
          "99.9% uptime SLA",
          "DDoS Protection",
          "Instant setup (1 minute)",
        ],
        cta: "Get started",
      },
    ],
  },
  "wordpress": {
    label: "WordPress",
    plans: [
      {
        name: "NH WP Basic",
        price: 1000,
        originalPrice: 1000,
        discount: "",
        billing: "/month (₦)",
        description: "Perfect for single WordPress website",
        features: [
          "1 Website",
          "5 GB SSD Storage",
          "Unlimited Bandwidth",
          "Free SSL Certificate",
          "Weekly Backups",
          "One-Click WordPress Installer",
          "24/7 WhatsApp Support",
        ],
        cta: "Get started",
      },
      {
        name: "NH WP Advance",
        price: 2500,
        originalPrice: 2500,
        discount: "",
        billing: "/month (₦)",
        description: "Best for growing WordPress businesses",
        popular: true,
        features: [
          "Host 3 Websites",
          "15 GB SSD Storage",
          "Unlimited Bandwidth",
          "Free SSL Certificate",
          "Daily Backups",
          "Auto WordPress Updates",
          "20 Email Accounts",
          "24/7 WhatsApp Support",
        ],
        cta: "Get started",
      },
      {
        name: "NH WP Turbo",
        price: 6500,
        originalPrice: 6500,
        discount: "",
        billing: "/month (₦)",
        description: "For unlimited WordPress hosting",
        features: [
          "Unlimited Websites",
          "Unlimited SSD Storage",
          "Unlimited Bandwidth",
          "Free SSL Certificate",
          "Premium Support",
          "Free .com.ng Domain (Yearly Plan)",
          "Unlimited Email Accounts",
          "Malware Scan + Security Monitor",
          "24/7 WhatsApp Support",
        ],
        cta: "Get started",
      },
    ],
  },
  "web-development": {
    label: "Web Development",
    plans: [
      {
        name: "Basic Web Development",
        price: 80000,
        originalPrice: 80000,
        discount: "",
        billing: "/project (₦)",
        description: "Responsive starter website",
        features: [
          "Up to 5 Pages",
          "Custom Design",
          "Mobile Friendly",
          "Contact Form",
          "Basic SEO Setup",
          "3-5 Days Delivery",
          "Responsive Design",
          "Cross-browser Compatibility",
          "Free SSL Certificate",
          "30-day post-launch support",
          "Perfect for small businesses & startups",
        ],
        cta: "Get started",
      },
      {
        name: "Standard Web Development",
        price: 150000,
        originalPrice: 150000,
        discount: "",
        billing: "/project (₦)",
        description: "Professional website with dynamic features",
        popular: true,
        features: [
          "Up to 10 Pages",
          "Blog or News Section",
          "Admin Dashboard (Basic CMS)",
          "Fully Responsive Design",
          "Brand-Aligned Styling",
          "SSL Enabled",
          "On-Page SEO + Google Index",
          "5-7 Days Delivery",
          "Content Management System",
          "Unlimited Revisions",
          "Great for growing businesses & bloggers",
        ],
        cta: "Get started",
      },
      {
        name: "Premium Web Development",
        price: 400000,
        originalPrice: 400000,
        discount: "",
        billing: "/project (₦)",
        description: "Full-scale custom solutions",
        features: [
          "Unlimited Pages",
          "E-commerce Store (Shop, Cart, Checkout)",
          "Custom CMS or Admin Panel",
          "Multi-language Support",
          "Advanced SEO Setup",
          "Security Features",
          "WhatsApp Integration",
          "UI/UX Optimized",
          "7-14 Days Delivery",
          "Payment Gateway Integration",
          "Unlimited Revisions",
          "₦20,000 setup fee included",
        ],
        cta: "Get started",
      },
    ],
  },
  "managed-hosting": {
    label: "Managed Hosting",
    plans: [
      {
        name: "Managed Basic",
        price: 32000,
        originalPrice: 32000,
        discount: "",
        billing: "/month (₦)",
        description: "Perfect for growing websites",
        features: [
          "2 CPU vCore",
          "2GB ECC RAM",
          "50GB SSD Storage",
          "500GB Monthly Bandwidth",
          "1 Static IPv4 Address",
          "Ubuntu, Debian, CentOS",
          "Free SSL Certificate",
          "Daily Backups",
          "Free Migration",
          "24/7 Expert Support",
          "7-day money-back guarantee",
        ],
        cta: "Get started",
      },
      {
        name: "Managed Pro",
        price: 62000,
        originalPrice: 62000,
        discount: "",
        billing: "/month (₦)",
        description: "Best for medium businesses",
        popular: true,
        features: [
          "4 CPU vCore",
          "4GB ECC RAM",
          "100GB SSD Storage",
          "1TB Monthly Bandwidth",
          "1 Static IPv4 Address",
          "Ubuntu, Debian, CentOS",
          "Free SSL Certificate",
          "Daily Backups",
          "Free Migration",
          "24/7 Expert Support",
          "Advanced Security (WAF + DDoS)",
          "Performance optimization",
          "7-day money-back guarantee",
        ],
        cta: "Get started",
      },
      {
        name: "Managed Enterprise",
        price: 102000,
        originalPrice: 102000,
        discount: "",
        billing: "/month (₦)",
        description: "For enterprise-scale operations",
        features: [
          "8 CPU vCore",
          "8GB ECC RAM",
          "200GB SSD Storage",
          "2TB Monthly Bandwidth",
          "2 Static IPv4 Addresses",
          "Ubuntu, Debian, CentOS",
          "Free SSL Certificate",
          "Daily & Weekly Backups",
          "Free Migration",
          "24/7 Expert Support",
          "Advanced Security (WAF + DDoS)",
          "Dedicated Account Manager",
          "Performance optimization",
          "7-day money-back guarantee",
        ],
        cta: "Get started",
      },
    ],
  },
  "premium-vpn": {
    label: "Premium VPN",
    plans: [
      {
        name: "Android VPN",
        price: 2300,
        originalPrice: 2300,
        discount: "",
        billing: "/month (₦)",
        description: "Perfect for mobile users",
        features: [
          "Unlimited Bandwidth",
          "2 Device Connections",
          "Fast Gaming Performance",
          "Anti-Tracking Protection",
          "Optimized for Android",
          "WireGuard / OpenVPN",
          "2 Cores CPU Power",
          "4 GB Assigned RAM",
          "USA-based servers",
          "Netflix US access",
          "24-hour money-back guarantee",
        ],
        cta: "Get started",
      },
      {
        name: "iPhone VPN",
        price: 3500,
        originalPrice: 3500,
        discount: "",
        billing: "/month (₦)",
        description: "Best for iOS devices",
        popular: true,
        features: [
          "Unlimited Bandwidth",
          "1 Device Connection",
          "High-Speed Streaming",
          "Military-Grade Encryption",
          "Optimized for iPhone & iPad",
          "WireGuard Protocol",
          "1 Core CPU Power",
          "2 GB Assigned RAM",
          "USA-based servers",
          "4K video streaming",
          "No-logs policy",
          "24-hour money-back guarantee",
        ],
        cta: "Get started",
      },
      {
        name: "PC & Mac VPN",
        price: 8500,
        originalPrice: 8500,
        discount: "",
        billing: "/month (₦)",
        description: "For ultimate protection",
        features: [
          "Unlimited Bandwidth",
          "5 Device Connections",
          "P2P & Torrent Friendly",
          "No-Logs Privacy Protection",
          "Works on Windows & macOS",
          "WireGuard / OpenVPN",
          "3 Cores CPU Power",
          "6 GB Assigned RAM",
          "USA-based servers",
          "Netflix & Disney+ access",
          "Banking app compatible",
          "24-hour money-back guarantee",
        ],
        cta: "Get started",
      },
    ],
  },
};
